on:
  push:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            name: linux
          - os: windows-latest
            arch: x64
            name: windows

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: yezz123/setup-uv@v4

      - name: Setup, install dependencies, build
        run: |
          uv sync
          uv run -m tool --test -- -v --junitxml=reports/${{ matrix.name }}-${{ matrix.arch }}.xml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.name }}-${{ matrix.arch }}
          path: reports/

  cov:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: reports/
      - uses: dorny/test-reporter@v1
        with:
          name: pytest
          path: "reports/*.xml"
          reporter: junit